### ISSUE TITLE
Cannot access database in setUpClass despite module level django_db marker

### ISSUE THREAD

**Issue by zsoldosp** [pytest-dev/pytest-django#117]
Test classes like the below 

* pass when run with the normal django test runner
* fails when run with py.test

```python
from django.utils.unittest import TestCase
from django.utils.decorators import classonlymethod
from django.contrib.auth.models import Group
import pytest

pytestmark = pytest.mark.django_db


class SimpleTest(TestCase):

    @classonlymethod
    def setUpClass(cls):
        Group.objects.create(name='foo')

    @classonlymethod
    def tearDownClass(cls):
        Group.objects.all().delete()

    def test_needs_db(self):
        self.assertEqual(1, Group.objects.count())
```

I couldn't create a proper unit test against pytest-django, but you can clone https://github.com/zsoldosp/pytest-django-unittest.TestCase.setUpClass-problem-repro as a start
(Note that the older versions are used due to https://github.com/pelme/pytest_django/issues/116 - I cannot check it against later versions)

requirements.txt:
```
Django==1.5
pytest==2.3.4
pytest-django==2.3.1
```

**Comment by pelme** [comment]
This should now be fixed in master. However, just putting things in `setUpClass`/`tearDownClass` will still not run in a transaction, but it will at least work in the same as with Django's default runner.

Django 1.8 solves this by introducing `setUpTestData` which properly takes care of rolling back the changes. With Django 1.8, `setUpClass` itself should also be transactional as long as the super setUpClass is called.

**Comment by blueyed** [comment]
Closing as per the previous comment(s); fixed in https://github.com/pytest-dev/pytest-django/commit/8a9aacbd835a49064ff8999137fa6ede34f3c520.
