### ISSUE TITLE
Easy fixture loading

### ISSUE THREAD

**Issue by johtso** [pytest-dev/pytest-django#13]
I noticed that the helper function for loading fixtures was removed. Possibly it wasn't worth keeping around the way it was, but I was wondering if there was scope for something more useful.

The simplest thing would be a function that takes a list of fixtures and loads them. What would be even better would be to be able to use a fixtures variable within a class and have it automatically loaded as with Django's TestCases.

It does seem like a bit of a step backwards from the functionality of Django's built in testing to have to do this:

``` python
    def setup_class(self):
        fixtures = ['base.json', 'things.json']

        for fixture in fixtures:
            call_command('loaddata', fixture)
```

..even if it is just a few lines of code.

What do you think?

**Comment by westurner** [comment]
This works. From https://flowfx.de/blog/populate-your-django-test-database-with-pytest-fixtures/ :

```python
import pytest

from django.core.management import call_command

@pytest.fixture(scope='session')
def django_db_setup(django_db_setup, django_db_blocker):
    with django_db_blocker.unblock():
        call_command('loaddata', 'potatoes_data.json')
```

```python
# tests/test_models.py

def test_my_potatoes(db, django_db_setup):
    # GIVEN a full database of potatoes, as provided by the django_db_setup fixture
    all_my_potatoes = Potato.objects.all()
```

**Comment by westurner** [comment]
> Current best practices do not advocate fixture loading from files, so it will not be supported in pytest-django.

The options for this, AFAIU, include:

- Loading fixtures as JSON and/or YAML as needed
  - Natively supported by the framework
- Generating Python source code
  - Ugly
- Trying to modify SQL dumps when migrations affect the underlying schema
  - Unnecessarily time consuming
  - A bit faster than JSON/YAML fixtures

**Comment by westurner** [comment]
For a large number of records, fixtures seem like a perfectly acceptable way to load test data into the database in Django. AFAIU, there is no plan to deprecate Django database fixtures due either to disuse or any best practices recommendations.

**Comment by deanmcginndm** [comment]
I think when we talk about best practices, we have to have the context of the practice.

On a staging site, it is possible that the fixtures described are previously installed from earlier generations. Whereas, sometimes this may not be the case when developing locally, or if you want to test a database from scratch.

The issue this presents is when an app with lots of different apps, which have custom calculations on the values stored in the database in order to present to a user.

In this use case, there may be data in the backend which drives these calculations, and whilst I completely agree, if I only need a user, then only create a user and that's all. Why do I need the back-end calculation in this case? Well, you don't. However, in the cases where one is creating tests that ensure the back-end calculations are correct, I would have to install each item I needed as a fixture, whereas Django would install them had they been placed in a class as is expected with the django test suite. Consider that there are use-cases for your repo that are beyond your personal projects :)

Best practice should be applied broadly and in a general fashion. I think being wary and cautious of over-applying the philosophy, else lose some of the automation conveniences that writing code satisfies.

**Comment by westurner** [comment]
Yeah there could be TestCase base/mixing classes with e.g. fixtureset class attrs that default to None or list config constants like ALL, or e.g. USER.

```python
class TestCase:
    fixtureset = None
    fixtureset = ALL
    fixtureset = USER
    fixtureset = [,]
```

**Comment by deanmcginndm** [comment]
```py
fixtures = ['book', 'author', 'etc...']
@pytest.fixture(autouse=True)
def django_fixtures_setup(django_db_setup, django_db_blocker):
    with django_db_blocker.unblock():
        call_command('loaddata', *['{}{}'.format(fixture, '.json') for fixture in fixtures])```
        
Above works fine also though
