### ISSUE TITLE
support custom test runners

### ISSUE THREAD

**Issue by matthewleon** [pytest-dev/pytest-django#185]
Currently, pytest runs the `setup_databases` methods from Django's `DiscoverRunner` to set up the database. It should support `setup_databases` from custom test runners as defined in the `TEST_RUNNER` setting.

**Comment by javrasya** [comment]
+1 for me.

**Comment by pelme** [comment]
pytest-django does not use Django's `DiscoverRunner` for running the tests - pytest is the test runner and that is the entire purpose of pytest-django.

In fact, DiscoverRunner is not even used by pytest-django in Django 1.6+ if you look carefully in https://github.com/pytest-dev/pytest-django/blob/master/pytest_django/compat.py

However, the problem of not being able to swap `setup_databases` to something different remains, but this will be solved with pytest fixtures. See https://github.com/pytest-dev/pytest-django/issues/37#issuecomment-68129900 for an example on this. When such fixtures can be defined, it will be trivial to the appropriate methods from another test runner class.

Closing this issue since custom test runners cannot be supported in this way.
