### ISSUE TITLE
pytest-pythonpath not a viable option?

### ISSUE THREAD

**Issue by ryankask** [pytest-dev/pytest-django#193]
I've tried using pytest-pythonpath as suggested in the docs but it seems like pytest-django is loaded before pytest-pythonpath.

Is there any other way to use a pytest hook or something internal to pytest to add a path to `PYTHONPATH`? 

I understand the other `PYTHONPATH` options but I'm looking for a solution using a pytest plugin or hook.

After a bit more investigation, if pytest-pythonpath used the `pytest_load_initial_conftests` hook instead of `pytest_configure`, it seems to work. 

I will submit a pull request to that project and leave this open since at the moment it appears the docs are wrong.

I've haven't used py.test too much so I may be missing something.

**Comment by pelme** [comment]
Hmm, it is tricky since pytest-django must be loaded very early (to allow importing things in the project `pytest_configure` hook).

pytest-django generally configures Django in the `pytest_load_initial_conftests` hook, you might be able to be able to run code before pytest-django by defining your own `pytest_load_initial_conftests` with the tryfirst marker:

```python
@pytest.mark.tryfirst
def pytest_load_initial_conftests(early_config, parser, args):
    sys.path.insert(...)
```

The behaviour of pytest-pythonpath could then maybe be changed to use `pytest_load_initial_conftests` instead.

**Comment by ryankask** [comment]
Thanks for the tip. I wasn't able to get it working but pytest-pythonpath has been updated to use the other hook.

Since the pytest-django docs are correct, I'm going to close this issue.

Once, again, thanks for your advice.

**Comment by pelme** [comment]
Oh, I see, great that it worked out and that pytest-pythonpath could use that hook instead! :)

**Comment by canassa** [comment]
I am also having this problem, but unlike @ryankask, the pytest-pythonpath patch didn't fix my problem. The funny thing is, the behaviour varies from machine to machine, in a OSX system the pytest-pythonpath was loaded first while in a Ubuntu system the pytest-django was loaded first.

I solved the problem by adding the `@pytest.mark.tryfirst` decorator as per @pelme recommendation. I opened [a PR](https://github.com/bigsassy/pytest-pythonpath/pull/6) to pytest-pythonpath.

Thanks!
