### ISSUE TITLE
Disable database code

### ISSUE THREAD

**Issue by prologic** [pytest-dev/pytest-django#217]
Is it possible to turn off all the database handling code in pytest-django?

We have a legacy app we're porting from Django 1.2 to 1.4 -- We have unit tests (_or rather integration tests_) and they're all heavily tied to a "live" database (_poor practices I know_) but there is no easy trivial way to fix/improve the test suite in a reasonable timeframe.

**Comment by pelme** [comment]
Do you access the live database from tests? I guess you could use `--reuse-db` in combination with specifying TEST settings in your settings file to point at the production database. If you intend to do this, please test it properly on a copy of your production database first since I have not tried this. :-)

There is a plan to split up/refactor the internal pytest-django fixtures (that handle the test database setup) to make them easier to override, which may help in this case, please provide some additional information on your setup and I'll try to take them into consideration.

**Comment by prologic** [comment]
Yeah many of our tests heavily rely on testing against a live database. It's however a copy of the production database snapshotted.

**Comment by pelme** [comment]
Ok, please try out `--reuse-db` in combination with defining the test database name explicitly via the TEST setting for the database!

**Comment by blueyed** [comment]
Closing, since it is supposed to be fixed in 3.0.
