### ISSUE TITLE
Can't use custom django TestRunner

### ISSUE THREAD

**Issue by Moerin** [pytest-dev/pytest-django#291]
Hi,

We use django in your project and we are eager to upgrade our test made originally with unittest.unittest or DjangoTestCase to py.test for access to its numerous functionnality.

During my implementation of pytest-django, I encountered some issues on code wich was written with other unittesting framework (ApiTestCase with is on override of DjangoTestCase), its try to create a database which is an unwanted behaviour.
In our test process we only use database for read-only purpose, with a custom TEST_RUNNER set in our django.settings.

I try to add DJANGO_SETTINGS_MODULE = project.settings.dev in pytest.ini with no success.
I study the source code of pytest-django and find the module compat.py which import the class DiscoverRunner to launch test.

What I want to know is there a way to change the TEST_RUNNER attribute chosen by pytest-django?
If so how can I do?

In other case I have made some modifications to get the TEST_RUNNER defined in django settings instead to import directly DiscoverRunner. I can create a pull request to do so.

Cheers.

**Comment by pelme** [comment]
When you are running tests with pytest+pytest-django, it is not possible to override `TEST_RUNNER` in a meaningful way, since it isn't actually used. pytest is the test runner. This has been suggested before, but it is not really possible (you can't have both a unittest test runner and pytest at the same time).

Django's TestCase implies having read/write access to the database. If you have tests that does not need the database, please subclass from `unittest.TestCase` or Django's `SimpleTestCase`. They are not coupled to the database, and pytest-django won't insist creating the database for them.

Good luck and please open a new issue if you find a bug in pytest-django!
