### ISSUE TITLE
db fixture always returns None

### ISSUE THREAD

**Issue by gjcarneiro** [pytest-dev/pytest-django#338]
Is it me being stupid, or the db fixture is always None?  Looking at the code:

```python
@pytest.fixture(scope='function')
def db(request, _django_db_setup, _django_cursor_wrapper):
    return _django_db_fixture_helper(False, request, _django_cursor_wrapper)
```
But `_django_db_fixture_helper` always returns None, it has no return statement at the end of the function!  

It is my first time using this plugin, so I could be missing something obvious.  My django settings have this:
```python

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
        }
}
```
The test is along these lines:
```python
@pytest.mark.parametrize("username,expected_credit_lim", [
...
])
def test_get_customer_credit_limit(db, username, expected_credit_lim):
	_create_tables(db)
	cur = db.cursor()
        ....
```

**Comment by gjcarneiro** [comment]
I'm beginning to think db being None is by design, and instead I need to just use `django.db.connection` directly.  If so, I must say this is not helpful. 

1) having a fixture with a value of None is very unintuitive, I suggest you just remove it as we then should use `@pytest.mark.django_db` instead

2) on the other hand, having a `db` fixture return a valid django connection that can be used for the test would be useful.

**Comment by blueyed** [comment]
> return a valid django connection that can be used for the test would be useful. 

Agreed.

**Comment by blueyed** [comment]
Well, there might be several connections involved (see https://github.com/pytest-dev/pytest-django/blob/485590ce41e6e41f710bf75de6de06245d6ab921/pytest_django/fixtures.py#L93-L100).
Should this be a list then?

As for `transactional_db` I just looked into getting to the Django `TransactionTestCase` to skip flushing tables on teardown - so in this specific case (where using `monkeypatch` seems to be better anyway) it would have been useful to return/have something in that regard.

So we could return a list of connections and the Django TestCase instance here maybe?!
On the other hand the fixture would need to get the list of connections itself for newer Django versions, so I am not really convinced.

**Comment by pelme** [comment]
The db fixture is mostly used internally to tie into the fixture system. The `django_db` mark basically exists to activate the `db` fixture, because the db fixture is weird by itself (since it does not return anything meaningful). We cannot get rid of the db fixture, because it is using the pytest fixture system to manage all of the database, which is a bit more involved.

We could return the connection, but I don't think it would be very helpful. When you need a django database connection or cursor, you should use `django.db.connection`/`django.db.connections`, which I think makes it look clearer. This is the way you normally would get a hold of the db connection when dealing with Django.

I've updated the code in question to remove the return statements, I hope that should make the intention clearer by reading the source.

Thanks for taking the time to submit the feedback! Please provide additional information on your use case if this is still unclear and could be improved! 😃
