### ISSUE TITLE
I did something silly

### ISSUE THREAD

**Issue by ionelmc** [pytest-dev/pytest-django#401]
I thought that editing on web would make a PR, but it did this: https://github.com/pytest-dev/pytest-django/commit/9972ec5a25d342a335dd9e6a334a5d39c8a86407 😳 

Uh ..... what now? @pelme

**Comment by pelme** [comment]
No worries! That happened to me too on a project where I did't realize I had commit access. The PR UI is really surprising.

Feel free to keep it as long as it doesn't break the test suite. Otherwise please revert it and make a proper PR. It is for sure a nice addition anyways. It is probably related to #297 and there are a bunch of cases that should be covered too some day but I won't mind having a better message for now. :)

**Comment by blueyed** [comment]
Builds are failing, but then let's just fix them, I'd say.

**Comment by pelme** [comment]
If you can do it soon(ish) that's fine but I'd rather not have other PRs fail because of this if they base off the current master.
