### ISSUE TITLE
Fix building the docs on RTD

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-django#449]
The building of the docs is currently broken: https://github.com/pytest-dev/pytest-django/pull/447#issuecomment-273681521

**Comment by bittner** [comment]
The details on the issue on summarized in the [Note section](https://github.com/pytest-dev/pytest-django/pull/447#issue-201311688) of PR #447.

https://github.com/pytest-dev/pytest/commit/e14e966d from the pytest project wouldn't fix it, because that refers to a local copy of the theme. Ours is supposed to be installed via pip (not sure how the static resources are pulled in from the virtualenv then, really, but it works when installed).

The [failing build](https://readthedocs.org/projects/pytest-django/builds/4914835/) tells me there is some `requirements.txt` that ReadTheDoc uses for installing dependencies:

``` bash
python /home/docs/checkouts/readthedocs.org/user_builds/pytest-django/envs/latest/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/pytest-django/.cache/pip -r/home/docs/checkouts/readthedocs.org/user_builds/pytest-django/checkouts/latest/requirements.txt
```

We need to add `Flask-Sphinx-Themes` to that file then the build should pass.

Afterwards, we need to see whether the "`make html` needs to run twice" is an issue that affects ReadTheDocs.

**Comment by bittner** [comment]
Can we try merging this?

**Comment by bittner** [comment]
Yay, we've got [nice-looking docs](https://pytest-django.readthedocs.io/)!  :tada:

**Comment by bittner** [comment]
Note that [we _do_ get a warning](https://readthedocs.org/projects/pytest-django/builds/4936127/) for the static files involved in the build process, though I haven't yet figured out if the final output of the docs is affected.
```
copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist
```

**Comment by blueyed** [comment]
@bittner 
Thanks for fixing it!

**Comment by pelme** [comment]
Just went and looked something up in the docs and they look amazing! Thanks again! :)

**Comment by bittner** [comment]
Thank you for the flowers!  :rose: 

If you browsed the docs using your mobile phone you may have noticed that the "Fork me on GitHub" ribbon is not fully responsive. I'm trying to [fix this upstream](https://github.com/pallets/flask-sphinx-themes/pull/16) in the theme's repository.
