### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sloria** [pytest-dev/pytest-django#473]
Do the maintainers have plans to cut the next release? A few projects at my job depend on some of the new features such as `django_assert_num_queries`.

If there are any blockers to release, I'd be glad to help out.

**Comment by auvipy** [comment]
1.11 based new release should be released @blueyed

**Comment by blueyed** [comment]
@pelme 
What do you say?
I am not even sure if I have permissions to do a release.

**Comment by ashwoods** [comment]
any news with this? Also glad to help out.

**Comment by p-himik** [comment]
Another problem is that Python 3.6 is specified as supported only in the unreleased version.

**Comment by pelme** [comment]
We need an updated change log. If anyone wants to prepare it, that would be very helpful and I will then do a release as soon as possible.

I've added @blueyed as a maintainer on PyPI, so that he can upload packages too!

To have more frequent releases, here are a couple of ways you can help that would be very very appreciated ❤️:
* The release process is now slightly manual (tagging, pushing tag to Github, building sdist+wheel, uploading to PyPI). This could be scriptet. I.e. just specifying those steps in a simple script that would take a version number as an argument. This would also need to be documented.

* The changelog management is slightly painful and prevents frequent releases.  Something like towncrier integrated with the above script would be very helpful.

* Help out doing releases. You would already need to be a pytest-django github maintainer or have some kind of track record in the pytest community. Let me know you PyPI username and I will add you as a maintainer. :)

@p-himik That is annoying, but just to be clear: the current release works fine with Python 3.6 (I use it myself daily).

**Comment by blueyed** [comment]
Thanks, @pelme.

Good ideas, I think using [towncrier](https://github.com/hawkowl/towncrier) might make sense, but am not sure if it is really better than skimming the git log manually once per release - pytest itself is using it, but there is more going on there in general.

**Comment by pelme** [comment]
It does not take too long to skim the changelog, but (speaking for myself), removing the small steps and automating releases would be nice and probably make it so that I would release more often. Ideally it would be nice to put out bugfix releases with pretty much each merged bugfix PR. It sucks to wait for bugfix releases. :)

**Comment by ashwoods** [comment]
I'll work on a tox config for managing releases as soon as I am back from vacations.

**Comment by MRigal** [comment]
@pelme what about a new release now? :)

**Comment by jedie** [comment]
> @pelme what about a new release now? :)

Yes, the PyPi package is very old and down't support django 1.11 :(

> The release process is now slightly manual (tagging, pushing tag to Github, building sdist+wheel, uploading to PyPI). This could be scriptet. I.e. just specifying those steps in a simple script that would take a version number as an argument. This would also need to be documented.

I make a `./setup.py publish` for this, with this code: https://github.com/jedie/python-code-snippets/blob/master/CodeSnippets/setup_publish.py

A real solution is something like https://github.com/zestsoftware/zest.releaser ... but never invest the time to evaluate it ;)

**Comment by sloria** [comment]
> > The release process is now slightly manual (tagging, pushing tag to Github, building sdist+wheel, uploading to PyPI). This could be scriptet. I.e. just specifying those steps in a simple script that would take a version number as an argument. This would also need to be documented.

> I make a ./setup.py publish for this, with this code: https://github.com/jedie/python-code-snippets/blob/master/CodeSnippets/setup_publish.py

I suggest automating a step further using [Travis Build Stages](https://docs.travis-ci.com/user/build-stages/). This will simplify the release process to just tagging and pushing. The PyPI release will happen automatically after tests pass.

I can send a PR setting this up when I get a chance. The maintainer will just need to add their PyPI username and encrypted password to make it work.

**Comment by blueyed** [comment]
> Yes, the PyPi package is very old and down't support django 1.11 :(

It does AFAIK?!

@sloria 
That would be nice IMHO.
AFAIK I am allowed to release to PyPI, so eventually we could use my credentials (or better create a separate user?), in case @pelme does not get a chance to do it himself.

**Comment by merwok** [comment]
> The release process is now slightly manual (tagging, pushing tag to Github, building sdist+wheel, uploading to PyPI).

Well it’s not too bad! :)  Automation is super nice but in the meantime one can live with these manual steps.

**Comment by axnsan12** [comment]
Any plans for this? There have been two major Django releases since this package was last pushed to PyPI, and for Django 2 support I have to install it directly from git.

**Comment by jedie** [comment]
No new release, yet ? :(

**Comment by OrangeDog** [comment]
There have been 81 commits and 504 days since the last release.

**Comment by blueyed** [comment]
Done: https://github.com/pytest-dev/pytest-django/releases/tag/3.2.0

**Comment by blueyed** [comment]
Hopefully https://travis-ci.org/pytest-dev/pytest-django/jobs/366444792 will work as expected to upload it to PyPI.

**Comment by auvipy** [comment]
not yet in pypi

**Comment by blueyed** [comment]
See https://github.com/pytest-dev/pytest-django/pull/590 / a96931e.

**Comment by blueyed** [comment]
Hopefully fixed with 3.2.1 (50063c4).

**Comment by blueyed** [comment]
https://pypi.python.org/pypi/pytest-django :fireworks:
