### ISSUE TITLE
Pytest cannot find settings

### ISSUE THREAD

**Issue by wolph** [pytest-dev/pytest-django#58]
The current working directory is not in the sys.path so it cannot find my settings file... now I'm wondering what would be the "clean" way to fix this.

I have no problem running other parts of py.test but the pytest_django module cannot find my settings.

My file structure is roughly like this:

```
project_directory/settings.py
project_directory/app_1/
project_directory/app_2/
project_directory/manage.py
```

Obviously `manage.py` has no problems importing the settings.

Py.test is being called like this:
`py.test --ds settings`

The exception:

```
_pytest.config.UsageError: Could not import settings 'settings' (Is it on sys.path? Is there an import error in the settings file?): No module named settings
```

What is the proper way to fix this? I know I can set the `PYTHONPATH` variable in my environment but that just seems hacky. Why won't pytest_django import from the current directory as you would expect?

**Comment by benjaoming** [comment]
Because this issue does indeed show up in search results, I'd like to add the most simple work-around for afaik:

 * Disable searching for `manage.py` by adding `django_find_project = false` to `pytest.ini`
 * Add `pytest-pythonpath` to test requirements or `pip install pytest-pythonpath`. This seems to add `cwd` to path automatically, so I didn't have to configure anything further.

http://pytest-django.readthedocs.io/en/latest/managing_python_path.html#managing-the-python-path-explicitly

**Comment by Natim** [comment]
I encountered this issue while having a bogus pytest.ini file:

```
[pytest]
DJANGO_SETTINGS_MODULE = "project.settings"
```

Removing the quotes fixed it:

```
[pytest]
DJANGO_SETTINGS_MODULE = project.settings
```
