### ISSUE TITLE
Inconsistent behaviour of db mark

### ISSUE THREAD

**Issue by canni** [pytest-dev/pytest-django#60]
When I was upgrading my project tests to use `pytest_django` plugin I've ran into this issue:

Currently `@pytest.mark.django_db` has (at least) 3 different behaviours

* When using simple function based test you forget to add marker, you get:
  `Failed: Database access not allowed, use the "django_db" mark to enable`

* When using tests as methods on `unitest2.TestCase` subclass you forget to add db marker, you get:
  `ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the NAME value.`

* When using test as methods on `django.test.TestCase` subclass, the marker is completely ignored (You're always allowed yo use DB inside)

Probably this should be documented as a feature ;) or fixed to behave concisely for all cases.

**Comment by pelme** [comment]
1) Is the expected behavior - explicit marking django_db is required
2) This is a bug and should be improved, it is tracked in #234
3) This is the expected behavior to be able to support existing Django test suites out of the box

I'm closing this, this issue, see #234 for follow up on the unittest2.TestCase problem
