### ISSUE TITLE
Error installing PANDAS( and others) but not Numpy in PYCHARM

### ISSUE THREAD

**Issue by OugoustEren** [pytest-dev/pytest-django#823]
Well I would like to install Pandas but I have a error each time that I try it. I re-install the program PyCharm and Python also but I the problem is still present. I do not know how to solve it.
Today is 12/Mar/2020
This is the error:
![image](https://user-images.githubusercontent.com/62121650/76574707-14c66700-648b-11ea-81d0-bfd1f0c37e84.png)

**Comment by luzfcb** [comment]
Hello @OugoustEren, your problem does not seem to be related to this project, so this may not be the right place to look for help, moreover, in general, images may not be very useful in finding out the cause of an error in programs.
The most important part of trying to find the cause of the problem is the execution log and traceback. In your case is all the text contained in the part where it is written: `Command output:`

That said, many years ago, when I was entering the world of programming, someone recommended me to read this link [1], and it was very useful to me. I hope it is useful for you too.

[1] http://catb.org/~esr/faqs/smart-questions.html
