### ISSUE TITLE
Tests accessing wrong database

### ISSUE THREAD

**Issue by roksys** [pytest-dev/pytest-django#892]
It seems that tests are accessing the wrong database.

In my settings.py I have the following

```
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'db',
        'USER': 'db',
        'PASSWORD': 'db',
        'TEST': {
            'ENGINE': 'django.contrib.gis.db.backends.spatialite',
            'NAME': ':memory:',
        }
    }
}
```

And when I run pytest, it still tries to access the default DB, instead of test one.

```
E       django.db.utils.OperationalError: FATAL:  Peer authentication failed for user "db"
I tried overriding the DB settings with a django_db_modify_db_settings
```

```
@pytest.fixture(scope='session')
def django_db_modify_db_settings():
    settings.DATABASES = settings.DATABASES['default']['TEST']

```
But no luck, I got the same error as above, because it tried to access the default DB.

**Comment by bluetech** [comment]
In the [Django docs](https://docs.djangoproject.com/en/3.1/ref/settings/#std:setting-DATABASE-TEST), `ENGINE` is not a listed as a setting that you can modify in `TEST`. So what happens probably is that it's trying to connect to a postgres DB named `:memory:`.

**Comment by egorgam** [comment]
@bluetech but what's a problem? There is no matter because @roksys used `django_db_modify_db_settings` fixture to reassign `DATABASES['default']` at all. Pair of years ago @blueyed recommended same workaround at same case https://github.com/pytest-dev/pytest-django/issues/643#issuecomment-460098826 ^^

It's very actual bug, because nowadays there is A LIE in django-pytest documentation: 

[Using an existing, external database for tests](https://pytest-django.readthedocs.io/en/latest/database.html#using-an-existing-external-database-for-tests) - in real, django-orm connection will use initial `settings.DATABASES["default"]` value, because it initiates before testing objects initiation. Reassigning of `django_db_setup` fixture is not working too.

And it's very frustrating, because there is no way to use non-default DATABASES value in tests. Only full reassign of DATABASES object in settings.py at application initiation is works (with `-k test` in sys.argv, or other same workaround...)

**Comment by vazkir** [comment]
Does somebody know if this finally has been fixed, so either django_db_modify_db_settings or django_db_setup work as expected? Or do I really have to create a separate settings file only to re-assign the original DATABASES value?
