### ISSUE TITLE
The fixture admin_client results in a crash when used with django_db(reset_sequences=True)

### ISSUE THREAD

**Issue by hwalinga** [pytest-dev/pytest-django#932]
When you use the fixture `admin_client` in combination with `reset_sequences=True` in django_db pytest mark, this results in a crash. 

```py
@pytest.mark.django_db(transaction=True, reset_sequences=True)
def test_something(admin_client):
```

Results in 

```
E               django.db.utils.IntegrityError: duplicate key value violates unique constraint "auth_user_pkey"
E               DETAIL:  Key (id)=(1) already exists.   
```

### Versions:
Django: 3.2.2
Pytest: 6.2.4
Pytest-Django: 4.2.0

**Comment by bluetech** [comment]
The `admin_client` requests the `admin_user` fixture which usually creates a new admin (superuser) user. Because the sequences are reset, the user is created with id 1, which already exists. Can you check which user this is? E.g. temporarily remove the `admin_client` and run

```
print(User.objects.get(id=1))
```

and see which user this is and where it was created.

**Comment by hwalinga** [comment]
Ah, I see one of our migrations sneaked a user in the database. Fixed it and works now. Thank you.
